package org.example.session;

public enum Step {

    START,

    CHOOSE_DIRECTION,
    CHOOSE_SOURCE_LANGUAGE,
    CHOOSE_TARGET_LANGUAGE,

    CHOOSE_DOCUMENT_TYPE,
    ENTER_PAGES,
    CHOOSE_URGENCY,

    CHOOSE_TRANSLATOR_SIGNATURE,
    CHOOSE_NOTARY_COPY,

    CHOOSE_APOSTILLE,

    CHOOSE_LEGALIZATION,
    CHOOSE_LEGALIZATION_DOCUMENT,
    CHOOSE_LEGALIZATION_URGENCY,

    RESULT

}
